//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.12.05 at 06:06:17 PM MSK 
//


package com.example.alpha.mock.model.ru.alfabank.ws.cs.eq.wscustomerbaseinfoinoutparms11;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ru.alfabank.ws.cs.eq.wscustomerbaseinfoinoutparms11 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ru.alfabank.ws.cs.eq.wscustomerbaseinfoinoutparms11
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link WSCustomerBaseInfoGetOutMainInfoT }
     * 
     */
    public WSCustomerBaseInfoGetOutMainInfoT createWSCustomerBaseInfoGetOutMainInfoT() {
        return new WSCustomerBaseInfoGetOutMainInfoT();
    }

    /**
     * Create an instance of {@link WSCustomerBaseInfoGetInParms }
     * 
     */
    public WSCustomerBaseInfoGetInParms createWSCustomerBaseInfoGetInParms() {
        return new WSCustomerBaseInfoGetInParms();
    }

    /**
     * Create an instance of {@link WSCustomerBaseInfoGetOutAdditionalInfoClientT }
     * 
     */
    public WSCustomerBaseInfoGetOutAdditionalInfoClientT createWSCustomerBaseInfoGetOutAdditionalInfoClientT() {
        return new WSCustomerBaseInfoGetOutAdditionalInfoClientT();
    }

    /**
     * Create an instance of {@link WSCustomerBaseInfoGetOutAdditionalInfoBankT }
     * 
     */
    public WSCustomerBaseInfoGetOutAdditionalInfoBankT createWSCustomerBaseInfoGetOutAdditionalInfoBankT() {
        return new WSCustomerBaseInfoGetOutAdditionalInfoBankT();
    }

    /**
     * Create an instance of {@link WSCustomerBaseInfoGetOutParms }
     * 
     */
    public WSCustomerBaseInfoGetOutParms createWSCustomerBaseInfoGetOutParms() {
        return new WSCustomerBaseInfoGetOutParms();
    }

}
