//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.12.05 at 06:06:17 PM MSK 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://WSCustomerBaseInfoInOutParms11.EQ.CS.ws.alfabank.ru")
package com.example.alpha.mock.model.ru.alfabank.ws.cs.eq.wscustomerbaseinfoinoutparms11;
