//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.12.05 at 06:06:17 PM MSK 
//


package com.example.alpha.mock.model.ru.alfabank.ws.cs.eq.wscustomerbaseinfoinoutparms11;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for WSCustomerBaseInfoGetOutAdditionalInfoBankT complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="WSCustomerBaseInfoGetOutAdditionalInfoBankT">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="fnm1" type="{http://WSCommonTypes10.CS.ws.alfabank.ru}WSTypeChar35"/>
 *         &lt;element name="fnm2" type="{http://WSCommonTypes10.CS.ws.alfabank.ru}WSTypeChar35"/>
 *         &lt;element name="fnm3" type="{http://WSCommonTypes10.CS.ws.alfabank.ru}WSTypeChar35"/>
 *         &lt;element name="bik" type="{http://WSCommonTypes10.CS.ws.alfabank.ru}WSTypeChar11"/>
 *         &lt;element name="ca" type="{http://WSCommonTypes10.CS.ws.alfabank.ru}WSTypeChar20"/>
 *         &lt;element name="regn" type="{http://WSCommonTypes10.CS.ws.alfabank.ru}WSTypeChar20"/>
 *         &lt;element name="rkc" type="{http://WSCommonTypes10.CS.ws.alfabank.ru}WSTypeChar9"/>
 *         &lt;element name="bnst" type="{http://WSCommonTypes10.CS.ws.alfabank.ru}WSTypeChar2"/>
 *         &lt;element name="stat" type="{http://WSCommonTypes10.CS.ws.alfabank.ru}WSTypeChar2"/>
 *         &lt;element name="okto" type="{http://WSCommonTypes10.CS.ws.alfabank.ru}WSTypeChar11"/>
 *         &lt;element name="okpo" type="{http://WSCommonTypes10.CS.ws.alfabank.ru}WSTypeChar20"/>
 *         &lt;element name="okhx" type="{http://WSCommonTypes10.CS.ws.alfabank.ru}WSTypeChar5"/>
 *         &lt;element name="okfs" type="{http://WSCommonTypes10.CS.ws.alfabank.ru}WSTypeChar2"/>
 *         &lt;element name="okpf" type="{http://WSCommonTypes10.CS.ws.alfabank.ru}WSTypeChar2"/>
 *         &lt;element name="okog" type="{http://WSCommonTypes10.CS.ws.alfabank.ru}WSTypeChar5"/>
 *         &lt;element name="foms" type="{http://WSCommonTypes10.CS.ws.alfabank.ru}WSTypeChar10"/>
 *         &lt;element name="npfn" type="{http://WSCommonTypes10.CS.ws.alfabank.ru}WSTypeChar10"/>
 *         &lt;element name="chrg" type="{http://WSCommonTypes10.CS.ws.alfabank.ru}WSTypeDecimal137"/>
 *         &lt;element name="kpp" type="{http://WSCommonTypes10.CS.ws.alfabank.ru}WSTypeChar9"/>
 *         &lt;element name="gni" type="{http://WSCommonTypes10.CS.ws.alfabank.ru}WSTypeChar3"/>
 *         &lt;element name="vali" type="{http://WSCommonTypes10.CS.ws.alfabank.ru}WSTypeChar1"/>
 *         &lt;element name="drli" type="{http://WSCommonTypes10.CS.ws.alfabank.ru}WSTypeChar1"/>
 *         &lt;element name="ruli" type="{http://WSCommonTypes10.CS.ws.alfabank.ru}WSTypeChar1"/>
 *         &lt;element name="grli" type="{http://WSCommonTypes10.CS.ws.alfabank.ru}WSTypeChar1"/>
 *         &lt;element name="elec" type="{http://WSCommonTypes10.CS.ws.alfabank.ru}WSTypeChar1"/>
 *         &lt;element name="mail" type="{http://WSCommonTypes10.CS.ws.alfabank.ru}WSTypeChar35"/>
 *         &lt;element name="dlg1" type="{http://WSCommonTypes10.CS.ws.alfabank.ru}WSTypeChar35"/>
 *         &lt;element name="fam1" type="{http://WSCommonTypes10.CS.ws.alfabank.ru}WSTypeChar35"/>
 *         &lt;element name="nam1" type="{http://WSCommonTypes10.CS.ws.alfabank.ru}WSTypeChar35"/>
 *         &lt;element name="par1" type="{http://WSCommonTypes10.CS.ws.alfabank.ru}WSTypeChar35"/>
 *         &lt;element name="pho1" type="{http://WSCommonTypes10.CS.ws.alfabank.ru}WSTypeChar35"/>
 *         &lt;element name="dlg2" type="{http://WSCommonTypes10.CS.ws.alfabank.ru}WSTypeChar35"/>
 *         &lt;element name="fam2" type="{http://WSCommonTypes10.CS.ws.alfabank.ru}WSTypeChar35"/>
 *         &lt;element name="nam2" type="{http://WSCommonTypes10.CS.ws.alfabank.ru}WSTypeChar35"/>
 *         &lt;element name="par2" type="{http://WSCommonTypes10.CS.ws.alfabank.ru}WSTypeChar35"/>
 *         &lt;element name="pho2" type="{http://WSCommonTypes10.CS.ws.alfabank.ru}WSTypeChar35"/>
 *         &lt;element name="regi" type="{http://WSCommonTypes10.CS.ws.alfabank.ru}WSTypeChar20"/>
 *         &lt;element name="dmgt" type="{http://WSCommonTypes10.CS.ws.alfabank.ru}WSTypeChar4"/>
 *         &lt;element name="tnal" type="{http://WSCommonTypes10.CS.ws.alfabank.ru}WSTypeChar4"/>
 *         &lt;element name="tnap" type="{http://WSCommonTypes10.CS.ws.alfabank.ru}WSTypeChar4"/>
 *         &lt;element name="tnam" type="{http://WSCommonTypes10.CS.ws.alfabank.ru}WSTypeChar4"/>
 *         &lt;element name="dtli" type="{http://WSCommonTypes10.CS.ws.alfabank.ru}WSTypeDate"/>
 *         &lt;element name="cnam" type="{http://WSCommonTypes10.CS.ws.alfabank.ru}WSTypeChar2"/>
 *         &lt;element name="nreg" type="{http://WSCommonTypes10.CS.ws.alfabank.ru}WSTypeChar20"/>
 *         &lt;element name="dtre" type="{http://WSCommonTypes10.CS.ws.alfabank.ru}WSTypeDate"/>
 *         &lt;element name="dacc" type="{http://WSCommonTypes10.CS.ws.alfabank.ru}WSTypeDate"/>
 *         &lt;element name="daco" type="{http://WSCommonTypes10.CS.ws.alfabank.ru}WSTypeDate"/>
 *         &lt;element name="clco" type="{http://WSCommonTypes10.CS.ws.alfabank.ru}WSTypeChar1"/>
 *         &lt;element name="ggni" type="{http://WSCommonTypes10.CS.ws.alfabank.ru}WSTypeChar30"/>
 *         &lt;element name="nalo" type="{http://WSCommonTypes10.CS.ws.alfabank.ru}WSTypeChar20"/>
 *         &lt;element name="dokn" type="{http://WSCommonTypes10.CS.ws.alfabank.ru}WSTypeDate"/>
 *         &lt;element name="okvd" type="{http://WSCommonTypes10.CS.ws.alfabank.ru}WSTypeChar8"/>
 *         &lt;element name="nids" type="{http://WSCommonTypes10.CS.ws.alfabank.ru}WSTypeChar15"/>
 *         &lt;element name="ncss" type="{http://WSCommonTypes10.CS.ws.alfabank.ru}WSTypeChar2"/>
 *         &lt;element name="real" type="{http://WSCommonTypes10.CS.ws.alfabank.ru}WSTypeChar4"/>
 *         &lt;element name="redc" type="{http://WSCommonTypes10.CS.ws.alfabank.ru}WSTypeDate"/>
 *         &lt;element name="rwsd" type="{http://WSCommonTypes10.CS.ws.alfabank.ru}WSTypeDecimal159"/>
 *         &lt;element name="ocsd" type="{http://WSCommonTypes10.CS.ws.alfabank.ru}WSTypeChar35"/>
 *         &lt;element name="user" type="{http://WSCommonTypes10.CS.ws.alfabank.ru}WSTypeChar4"/>
 *         &lt;element name="sogr" type="{http://WSCommonTypes10.CS.ws.alfabank.ru}WSTypeChar2"/>
 *         &lt;element name="nogr" type="{http://WSCommonTypes10.CS.ws.alfabank.ru}WSTypeChar9"/>
 *         &lt;element name="bsp1" type="{http://WSCommonTypes10.CS.ws.alfabank.ru}WSTypeChar5"/>
 *         &lt;element name="bsp2" type="{http://WSCommonTypes10.CS.ws.alfabank.ru}WSTypeChar12"/>
 *         &lt;element name="kno" type="{http://WSCommonTypes10.CS.ws.alfabank.ru}WSTypeChar4"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "WSCustomerBaseInfoGetOutAdditionalInfoBankT", propOrder = {
    "fnm1",
    "fnm2",
    "fnm3",
    "bik",
    "ca",
    "regn",
    "rkc",
    "bnst",
    "stat",
    "okto",
    "okpo",
    "okhx",
    "okfs",
    "okpf",
    "okog",
    "foms",
    "npfn",
    "chrg",
    "kpp",
    "gni",
    "vali",
    "drli",
    "ruli",
    "grli",
    "elec",
    "mail",
    "dlg1",
    "fam1",
    "nam1",
    "par1",
    "pho1",
    "dlg2",
    "fam2",
    "nam2",
    "par2",
    "pho2",
    "regi",
    "dmgt",
    "tnal",
    "tnap",
    "tnam",
    "dtli",
    "cnam",
    "nreg",
    "dtre",
    "dacc",
    "daco",
    "clco",
    "ggni",
    "nalo",
    "dokn",
    "okvd",
    "nids",
    "ncss",
    "real",
    "redc",
    "rwsd",
    "ocsd",
    "user",
    "sogr",
    "nogr",
    "bsp1",
    "bsp2",
    "kno"
})
public class WSCustomerBaseInfoGetOutAdditionalInfoBankT {

    @XmlElement(required = true)
    protected String fnm1;
    @XmlElement(required = true)
    protected String fnm2;
    @XmlElement(required = true)
    protected String fnm3;
    @XmlElement(required = true)
    protected String bik;
    @XmlElement(required = true)
    protected String ca;
    @XmlElement(required = true)
    protected String regn;
    @XmlElement(required = true)
    protected String rkc;
    @XmlElement(required = true)
    protected String bnst;
    @XmlElement(required = true)
    protected String stat;
    @XmlElement(required = true)
    protected String okto;
    @XmlElement(required = true)
    protected String okpo;
    @XmlElement(required = true)
    protected String okhx;
    @XmlElement(required = true)
    protected String okfs;
    @XmlElement(required = true)
    protected String okpf;
    @XmlElement(required = true)
    protected String okog;
    @XmlElement(required = true)
    protected String foms;
    @XmlElement(required = true)
    protected String npfn;
    @XmlElement(required = true)
    protected BigDecimal chrg;
    @XmlElement(required = true)
    protected String kpp;
    @XmlElement(required = true)
    protected String gni;
    @XmlElement(required = true)
    protected String vali;
    @XmlElement(required = true)
    protected String drli;
    @XmlElement(required = true)
    protected String ruli;
    @XmlElement(required = true)
    protected String grli;
    @XmlElement(required = true)
    protected String elec;
    @XmlElement(required = true)
    protected String mail;
    @XmlElement(required = true)
    protected String dlg1;
    @XmlElement(required = true)
    protected String fam1;
    @XmlElement(required = true)
    protected String nam1;
    @XmlElement(required = true)
    protected String par1;
    @XmlElement(required = true)
    protected String pho1;
    @XmlElement(required = true)
    protected String dlg2;
    @XmlElement(required = true)
    protected String fam2;
    @XmlElement(required = true)
    protected String nam2;
    @XmlElement(required = true)
    protected String par2;
    @XmlElement(required = true)
    protected String pho2;
    @XmlElement(required = true)
    protected String regi;
    @XmlElement(required = true)
    protected String dmgt;
    @XmlElement(required = true)
    protected String tnal;
    @XmlElement(required = true)
    protected String tnap;
    @XmlElement(required = true)
    protected String tnam;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dtli;
    @XmlElement(required = true)
    protected String cnam;
    @XmlElement(required = true)
    protected String nreg;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dtre;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dacc;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar daco;
    @XmlElement(required = true)
    protected String clco;
    @XmlElement(required = true)
    protected String ggni;
    @XmlElement(required = true)
    protected String nalo;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dokn;
    @XmlElement(required = true)
    protected String okvd;
    @XmlElement(required = true)
    protected String nids;
    @XmlElement(required = true)
    protected String ncss;
    @XmlElement(required = true)
    protected String real;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar redc;
    @XmlElement(required = true)
    protected BigDecimal rwsd;
    @XmlElement(required = true)
    protected String ocsd;
    @XmlElement(required = true)
    protected String user;
    @XmlElement(required = true)
    protected String sogr;
    @XmlElement(required = true)
    protected String nogr;
    @XmlElement(required = true)
    protected String bsp1;
    @XmlElement(required = true)
    protected String bsp2;
    @XmlElement(required = true)
    protected String kno;

    /**
     * Gets the value of the fnm1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFnm1() {
        return fnm1;
    }

    /**
     * Sets the value of the fnm1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFnm1(String value) {
        this.fnm1 = value;
    }

    /**
     * Gets the value of the fnm2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFnm2() {
        return fnm2;
    }

    /**
     * Sets the value of the fnm2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFnm2(String value) {
        this.fnm2 = value;
    }

    /**
     * Gets the value of the fnm3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFnm3() {
        return fnm3;
    }

    /**
     * Sets the value of the fnm3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFnm3(String value) {
        this.fnm3 = value;
    }

    /**
     * Gets the value of the bik property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBik() {
        return bik;
    }

    /**
     * Sets the value of the bik property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBik(String value) {
        this.bik = value;
    }

    /**
     * Gets the value of the ca property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCa() {
        return ca;
    }

    /**
     * Sets the value of the ca property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCa(String value) {
        this.ca = value;
    }

    /**
     * Gets the value of the regn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegn() {
        return regn;
    }

    /**
     * Sets the value of the regn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegn(String value) {
        this.regn = value;
    }

    /**
     * Gets the value of the rkc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRkc() {
        return rkc;
    }

    /**
     * Sets the value of the rkc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRkc(String value) {
        this.rkc = value;
    }

    /**
     * Gets the value of the bnst property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBnst() {
        return bnst;
    }

    /**
     * Sets the value of the bnst property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBnst(String value) {
        this.bnst = value;
    }

    /**
     * Gets the value of the stat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStat() {
        return stat;
    }

    /**
     * Sets the value of the stat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStat(String value) {
        this.stat = value;
    }

    /**
     * Gets the value of the okto property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOkto() {
        return okto;
    }

    /**
     * Sets the value of the okto property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOkto(String value) {
        this.okto = value;
    }

    /**
     * Gets the value of the okpo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOkpo() {
        return okpo;
    }

    /**
     * Sets the value of the okpo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOkpo(String value) {
        this.okpo = value;
    }

    /**
     * Gets the value of the okhx property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOkhx() {
        return okhx;
    }

    /**
     * Sets the value of the okhx property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOkhx(String value) {
        this.okhx = value;
    }

    /**
     * Gets the value of the okfs property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOkfs() {
        return okfs;
    }

    /**
     * Sets the value of the okfs property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOkfs(String value) {
        this.okfs = value;
    }

    /**
     * Gets the value of the okpf property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOkpf() {
        return okpf;
    }

    /**
     * Sets the value of the okpf property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOkpf(String value) {
        this.okpf = value;
    }

    /**
     * Gets the value of the okog property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOkog() {
        return okog;
    }

    /**
     * Sets the value of the okog property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOkog(String value) {
        this.okog = value;
    }

    /**
     * Gets the value of the foms property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFoms() {
        return foms;
    }

    /**
     * Sets the value of the foms property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFoms(String value) {
        this.foms = value;
    }

    /**
     * Gets the value of the npfn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNpfn() {
        return npfn;
    }

    /**
     * Sets the value of the npfn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNpfn(String value) {
        this.npfn = value;
    }

    /**
     * Gets the value of the chrg property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getChrg() {
        return chrg;
    }

    /**
     * Sets the value of the chrg property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setChrg(BigDecimal value) {
        this.chrg = value;
    }

    /**
     * Gets the value of the kpp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKpp() {
        return kpp;
    }

    /**
     * Sets the value of the kpp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKpp(String value) {
        this.kpp = value;
    }

    /**
     * Gets the value of the gni property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGni() {
        return gni;
    }

    /**
     * Sets the value of the gni property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGni(String value) {
        this.gni = value;
    }

    /**
     * Gets the value of the vali property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVali() {
        return vali;
    }

    /**
     * Sets the value of the vali property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVali(String value) {
        this.vali = value;
    }

    /**
     * Gets the value of the drli property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDrli() {
        return drli;
    }

    /**
     * Sets the value of the drli property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDrli(String value) {
        this.drli = value;
    }

    /**
     * Gets the value of the ruli property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRuli() {
        return ruli;
    }

    /**
     * Sets the value of the ruli property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRuli(String value) {
        this.ruli = value;
    }

    /**
     * Gets the value of the grli property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGrli() {
        return grli;
    }

    /**
     * Sets the value of the grli property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGrli(String value) {
        this.grli = value;
    }

    /**
     * Gets the value of the elec property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getElec() {
        return elec;
    }

    /**
     * Sets the value of the elec property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setElec(String value) {
        this.elec = value;
    }

    /**
     * Gets the value of the mail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMail() {
        return mail;
    }

    /**
     * Sets the value of the mail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMail(String value) {
        this.mail = value;
    }

    /**
     * Gets the value of the dlg1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDlg1() {
        return dlg1;
    }

    /**
     * Sets the value of the dlg1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDlg1(String value) {
        this.dlg1 = value;
    }

    /**
     * Gets the value of the fam1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFam1() {
        return fam1;
    }

    /**
     * Sets the value of the fam1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFam1(String value) {
        this.fam1 = value;
    }

    /**
     * Gets the value of the nam1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNam1() {
        return nam1;
    }

    /**
     * Sets the value of the nam1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNam1(String value) {
        this.nam1 = value;
    }

    /**
     * Gets the value of the par1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPar1() {
        return par1;
    }

    /**
     * Sets the value of the par1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPar1(String value) {
        this.par1 = value;
    }

    /**
     * Gets the value of the pho1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPho1() {
        return pho1;
    }

    /**
     * Sets the value of the pho1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPho1(String value) {
        this.pho1 = value;
    }

    /**
     * Gets the value of the dlg2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDlg2() {
        return dlg2;
    }

    /**
     * Sets the value of the dlg2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDlg2(String value) {
        this.dlg2 = value;
    }

    /**
     * Gets the value of the fam2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFam2() {
        return fam2;
    }

    /**
     * Sets the value of the fam2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFam2(String value) {
        this.fam2 = value;
    }

    /**
     * Gets the value of the nam2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNam2() {
        return nam2;
    }

    /**
     * Sets the value of the nam2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNam2(String value) {
        this.nam2 = value;
    }

    /**
     * Gets the value of the par2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPar2() {
        return par2;
    }

    /**
     * Sets the value of the par2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPar2(String value) {
        this.par2 = value;
    }

    /**
     * Gets the value of the pho2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPho2() {
        return pho2;
    }

    /**
     * Sets the value of the pho2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPho2(String value) {
        this.pho2 = value;
    }

    /**
     * Gets the value of the regi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegi() {
        return regi;
    }

    /**
     * Sets the value of the regi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegi(String value) {
        this.regi = value;
    }

    /**
     * Gets the value of the dmgt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDmgt() {
        return dmgt;
    }

    /**
     * Sets the value of the dmgt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDmgt(String value) {
        this.dmgt = value;
    }

    /**
     * Gets the value of the tnal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTnal() {
        return tnal;
    }

    /**
     * Sets the value of the tnal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTnal(String value) {
        this.tnal = value;
    }

    /**
     * Gets the value of the tnap property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTnap() {
        return tnap;
    }

    /**
     * Sets the value of the tnap property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTnap(String value) {
        this.tnap = value;
    }

    /**
     * Gets the value of the tnam property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTnam() {
        return tnam;
    }

    /**
     * Sets the value of the tnam property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTnam(String value) {
        this.tnam = value;
    }

    /**
     * Gets the value of the dtli property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDtli() {
        return dtli;
    }

    /**
     * Sets the value of the dtli property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDtli(XMLGregorianCalendar value) {
        this.dtli = value;
    }

    /**
     * Gets the value of the cnam property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCnam() {
        return cnam;
    }

    /**
     * Sets the value of the cnam property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCnam(String value) {
        this.cnam = value;
    }

    /**
     * Gets the value of the nreg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNreg() {
        return nreg;
    }

    /**
     * Sets the value of the nreg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNreg(String value) {
        this.nreg = value;
    }

    /**
     * Gets the value of the dtre property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDtre() {
        return dtre;
    }

    /**
     * Sets the value of the dtre property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDtre(XMLGregorianCalendar value) {
        this.dtre = value;
    }

    /**
     * Gets the value of the dacc property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDacc() {
        return dacc;
    }

    /**
     * Sets the value of the dacc property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDacc(XMLGregorianCalendar value) {
        this.dacc = value;
    }

    /**
     * Gets the value of the daco property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDaco() {
        return daco;
    }

    /**
     * Sets the value of the daco property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDaco(XMLGregorianCalendar value) {
        this.daco = value;
    }

    /**
     * Gets the value of the clco property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClco() {
        return clco;
    }

    /**
     * Sets the value of the clco property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClco(String value) {
        this.clco = value;
    }

    /**
     * Gets the value of the ggni property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGgni() {
        return ggni;
    }

    /**
     * Sets the value of the ggni property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGgni(String value) {
        this.ggni = value;
    }

    /**
     * Gets the value of the nalo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNalo() {
        return nalo;
    }

    /**
     * Sets the value of the nalo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNalo(String value) {
        this.nalo = value;
    }

    /**
     * Gets the value of the dokn property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDokn() {
        return dokn;
    }

    /**
     * Sets the value of the dokn property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDokn(XMLGregorianCalendar value) {
        this.dokn = value;
    }

    /**
     * Gets the value of the okvd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOkvd() {
        return okvd;
    }

    /**
     * Sets the value of the okvd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOkvd(String value) {
        this.okvd = value;
    }

    /**
     * Gets the value of the nids property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNids() {
        return nids;
    }

    /**
     * Sets the value of the nids property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNids(String value) {
        this.nids = value;
    }

    /**
     * Gets the value of the ncss property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNcss() {
        return ncss;
    }

    /**
     * Sets the value of the ncss property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNcss(String value) {
        this.ncss = value;
    }

    /**
     * Gets the value of the real property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReal() {
        return real;
    }

    /**
     * Sets the value of the real property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReal(String value) {
        this.real = value;
    }

    /**
     * Gets the value of the redc property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getRedc() {
        return redc;
    }

    /**
     * Sets the value of the redc property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setRedc(XMLGregorianCalendar value) {
        this.redc = value;
    }

    /**
     * Gets the value of the rwsd property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getRwsd() {
        return rwsd;
    }

    /**
     * Sets the value of the rwsd property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setRwsd(BigDecimal value) {
        this.rwsd = value;
    }

    /**
     * Gets the value of the ocsd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOcsd() {
        return ocsd;
    }

    /**
     * Sets the value of the ocsd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOcsd(String value) {
        this.ocsd = value;
    }

    /**
     * Gets the value of the user property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUser() {
        return user;
    }

    /**
     * Sets the value of the user property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUser(String value) {
        this.user = value;
    }

    /**
     * Gets the value of the sogr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSogr() {
        return sogr;
    }

    /**
     * Sets the value of the sogr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSogr(String value) {
        this.sogr = value;
    }

    /**
     * Gets the value of the nogr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNogr() {
        return nogr;
    }

    /**
     * Sets the value of the nogr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNogr(String value) {
        this.nogr = value;
    }

    /**
     * Gets the value of the bsp1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBsp1() {
        return bsp1;
    }

    /**
     * Sets the value of the bsp1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBsp1(String value) {
        this.bsp1 = value;
    }

    /**
     * Gets the value of the bsp2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBsp2() {
        return bsp2;
    }

    /**
     * Sets the value of the bsp2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBsp2(String value) {
        this.bsp2 = value;
    }

    /**
     * Gets the value of the kno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKno() {
        return kno;
    }

    /**
     * Sets the value of the kno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKno(String value) {
        this.kno = value;
    }

}
