//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.12.05 at 06:06:17 PM MSK 
//


package com.example.alpha.mock.model.ru.alfabank.ws.cs.eq.wscustomerbaseinfoinoutparms11;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import ru.alfabank.ws.cs.wscommontypes10.WSCommonOutParms;


/**
 * <p>Java class for WSCustomerBaseInfoGetOutParms complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="WSCustomerBaseInfoGetOutParms">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="outCommonParms" type="{http://WSCommonTypes10.CS.ws.alfabank.ru}WSCommonOutParms"/>
 *         &lt;element name="mainInfo" type="{http://WSCustomerBaseInfoInOutParms11.EQ.CS.ws.alfabank.ru}WSCustomerBaseInfoGetOutMainInfoT"/>
 *         &lt;element name="additionalInfoGroup" type="{http://WSCommonTypes10.CS.ws.alfabank.ru}WSTypeChar5"/>
 *         &lt;element name="additionalInfoClient" type="{http://WSCustomerBaseInfoInOutParms11.EQ.CS.ws.alfabank.ru}WSCustomerBaseInfoGetOutAdditionalInfoClientT" minOccurs="0"/>
 *         &lt;element name="additionalInfoBank" type="{http://WSCustomerBaseInfoInOutParms11.EQ.CS.ws.alfabank.ru}WSCustomerBaseInfoGetOutAdditionalInfoBankT" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "WSCustomerBaseInfoGetOutParms", propOrder = {
    "outCommonParms",
    "mainInfo",
    "additionalInfoGroup",
    "additionalInfoClient",
    "additionalInfoBank"
})
public class WSCustomerBaseInfoGetOutParms {

    @XmlElement(required = true)
    protected WSCommonOutParms outCommonParms;
    @XmlElement(required = true)
    protected WSCustomerBaseInfoGetOutMainInfoT mainInfo;
    @XmlElement(required = true)
    protected String additionalInfoGroup;
    protected WSCustomerBaseInfoGetOutAdditionalInfoClientT additionalInfoClient;
    protected WSCustomerBaseInfoGetOutAdditionalInfoBankT additionalInfoBank;

    /**
     * Gets the value of the outCommonParms property.
     * 
     * @return
     *     possible object is
     *     {@link WSCommonOutParms }
     *     
     */
    public WSCommonOutParms getOutCommonParms() {
        return outCommonParms;
    }

    /**
     * Sets the value of the outCommonParms property.
     * 
     * @param value
     *     allowed object is
     *     {@link WSCommonOutParms }
     *     
     */
    public void setOutCommonParms(WSCommonOutParms value) {
        this.outCommonParms = value;
    }

    /**
     * Gets the value of the mainInfo property.
     * 
     * @return
     *     possible object is
     *     {@link WSCustomerBaseInfoGetOutMainInfoT }
     *     
     */
    public WSCustomerBaseInfoGetOutMainInfoT getMainInfo() {
        return mainInfo;
    }

    /**
     * Sets the value of the mainInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link WSCustomerBaseInfoGetOutMainInfoT }
     *     
     */
    public void setMainInfo(WSCustomerBaseInfoGetOutMainInfoT value) {
        this.mainInfo = value;
    }

    /**
     * Gets the value of the additionalInfoGroup property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdditionalInfoGroup() {
        return additionalInfoGroup;
    }

    /**
     * Sets the value of the additionalInfoGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdditionalInfoGroup(String value) {
        this.additionalInfoGroup = value;
    }

    /**
     * Gets the value of the additionalInfoClient property.
     * 
     * @return
     *     possible object is
     *     {@link WSCustomerBaseInfoGetOutAdditionalInfoClientT }
     *     
     */
    public WSCustomerBaseInfoGetOutAdditionalInfoClientT getAdditionalInfoClient() {
        return additionalInfoClient;
    }

    /**
     * Sets the value of the additionalInfoClient property.
     * 
     * @param value
     *     allowed object is
     *     {@link WSCustomerBaseInfoGetOutAdditionalInfoClientT }
     *     
     */
    public void setAdditionalInfoClient(WSCustomerBaseInfoGetOutAdditionalInfoClientT value) {
        this.additionalInfoClient = value;
    }

    /**
     * Gets the value of the additionalInfoBank property.
     * 
     * @return
     *     possible object is
     *     {@link WSCustomerBaseInfoGetOutAdditionalInfoBankT }
     *     
     */
    public WSCustomerBaseInfoGetOutAdditionalInfoBankT getAdditionalInfoBank() {
        return additionalInfoBank;
    }

    /**
     * Sets the value of the additionalInfoBank property.
     * 
     * @param value
     *     allowed object is
     *     {@link WSCustomerBaseInfoGetOutAdditionalInfoBankT }
     *     
     */
    public void setAdditionalInfoBank(WSCustomerBaseInfoGetOutAdditionalInfoBankT value) {
        this.additionalInfoBank = value;
    }

}
