//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.12.05 at 06:06:17 PM MSK 
//


package com.example.alpha.mock.model.ru.alfabank.ws.cs.eq.wscustomerbaseinfoinoutparms11;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for WSCustomerBaseInfoGetOutAdditionalInfoClientT complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="WSCustomerBaseInfoGetOutAdditionalInfoClientT">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="fnm1" type="{http://WSCommonTypes10.CS.ws.alfabank.ru}WSTypeChar35"/>
 *         &lt;element name="fnm2" type="{http://WSCommonTypes10.CS.ws.alfabank.ru}WSTypeChar35"/>
 *         &lt;element name="fnm3" type="{http://WSCommonTypes10.CS.ws.alfabank.ru}WSTypeChar35"/>
 *         &lt;element name="bikr" type="{http://WSCommonTypes10.CS.ws.alfabank.ru}WSTypeChar9"/>
 *         &lt;element name="bnkn" type="{http://WSCommonTypes10.CS.ws.alfabank.ru}WSTypeChar35"/>
 *         &lt;element name="ca" type="{http://WSCommonTypes10.CS.ws.alfabank.ru}WSTypeChar20"/>
 *         &lt;element name="shr" type="{http://WSCommonTypes10.CS.ws.alfabank.ru}WSTypeChar20"/>
 *         &lt;element name="shv" type="{http://WSCommonTypes10.CS.ws.alfabank.ru}WSTypeChar20"/>
 *         &lt;element name="shb" type="{http://WSCommonTypes10.CS.ws.alfabank.ru}WSTypeChar20"/>
 *         &lt;element name="okhx" type="{http://WSCommonTypes10.CS.ws.alfabank.ru}WSTypeChar5"/>
 *         &lt;element name="okto" type="{http://WSCommonTypes10.CS.ws.alfabank.ru}WSTypeChar11"/>
 *         &lt;element name="okpo" type="{http://WSCommonTypes10.CS.ws.alfabank.ru}WSTypeChar20"/>
 *         &lt;element name="okfs" type="{http://WSCommonTypes10.CS.ws.alfabank.ru}WSTypeChar2"/>
 *         &lt;element name="okpf" type="{http://WSCommonTypes10.CS.ws.alfabank.ru}WSTypeChar2"/>
 *         &lt;element name="okog" type="{http://WSCommonTypes10.CS.ws.alfabank.ru}WSTypeChar5"/>
 *         &lt;element name="dlg1" type="{http://WSCommonTypes10.CS.ws.alfabank.ru}WSTypeChar35"/>
 *         &lt;element name="fam1" type="{http://WSCommonTypes10.CS.ws.alfabank.ru}WSTypeChar35"/>
 *         &lt;element name="nam1" type="{http://WSCommonTypes10.CS.ws.alfabank.ru}WSTypeChar35"/>
 *         &lt;element name="par1" type="{http://WSCommonTypes10.CS.ws.alfabank.ru}WSTypeChar35"/>
 *         &lt;element name="pho1" type="{http://WSCommonTypes10.CS.ws.alfabank.ru}WSTypeChar35"/>
 *         &lt;element name="dlg2" type="{http://WSCommonTypes10.CS.ws.alfabank.ru}WSTypeChar35"/>
 *         &lt;element name="fam2" type="{http://WSCommonTypes10.CS.ws.alfabank.ru}WSTypeChar35"/>
 *         &lt;element name="nam2" type="{http://WSCommonTypes10.CS.ws.alfabank.ru}WSTypeChar35"/>
 *         &lt;element name="par2" type="{http://WSCommonTypes10.CS.ws.alfabank.ru}WSTypeChar35"/>
 *         &lt;element name="pho2" type="{http://WSCommonTypes10.CS.ws.alfabank.ru}WSTypeChar35"/>
 *         &lt;element name="clco" type="{http://WSCommonTypes10.CS.ws.alfabank.ru}WSTypeChar1"/>
 *         &lt;element name="dacc" type="{http://WSCommonTypes10.CS.ws.alfabank.ru}WSTypeDate"/>
 *         &lt;element name="daco" type="{http://WSCommonTypes10.CS.ws.alfabank.ru}WSTypeDate"/>
 *         &lt;element name="klba" type="{http://WSCommonTypes10.CS.ws.alfabank.ru}WSTypeChar2"/>
 *         &lt;element name="perp" type="{http://WSCommonTypes10.CS.ws.alfabank.ru}WSTypeChar1"/>
 *         &lt;element name="cred" type="{http://WSCommonTypes10.CS.ws.alfabank.ru}WSTypeChar1"/>
 *         &lt;element name="kpp" type="{http://WSCommonTypes10.CS.ws.alfabank.ru}WSTypeChar9"/>
 *         &lt;element name="gni" type="{http://WSCommonTypes10.CS.ws.alfabank.ru}WSTypeChar3"/>
 *         &lt;element name="ggni" type="{http://WSCommonTypes10.CS.ws.alfabank.ru}WSTypeChar30"/>
 *         &lt;element name="foms" type="{http://WSCommonTypes10.CS.ws.alfabank.ru}WSTypeChar10"/>
 *         &lt;element name="npfn" type="{http://WSCommonTypes10.CS.ws.alfabank.ru}WSTypeChar10"/>
 *         &lt;element name="dmgt" type="{http://WSCommonTypes10.CS.ws.alfabank.ru}WSTypeChar4"/>
 *         &lt;element name="dtre" type="{http://WSCommonTypes10.CS.ws.alfabank.ru}WSTypeDate"/>
 *         &lt;element name="nreg" type="{http://WSCommonTypes10.CS.ws.alfabank.ru}WSTypeChar20"/>
 *         &lt;element name="tnal" type="{http://WSCommonTypes10.CS.ws.alfabank.ru}WSTypeChar4"/>
 *         &lt;element name="tnap" type="{http://WSCommonTypes10.CS.ws.alfabank.ru}WSTypeChar4"/>
 *         &lt;element name="tnam" type="{http://WSCommonTypes10.CS.ws.alfabank.ru}WSTypeChar4"/>
 *         &lt;element name="cnam" type="{http://WSCommonTypes10.CS.ws.alfabank.ru}WSTypeChar2"/>
 *         &lt;element name="kotn" type="{http://WSCommonTypes10.CS.ws.alfabank.ru}WSTypeChar2"/>
 *         &lt;element name="mail" type="{http://WSCommonTypes10.CS.ws.alfabank.ru}WSTypeChar35"/>
 *         &lt;element name="namr" type="{http://WSCommonTypes10.CS.ws.alfabank.ru}WSTypeChar35"/>
 *         &lt;element name="phor" type="{http://WSCommonTypes10.CS.ws.alfabank.ru}WSTypeChar35"/>
 *         &lt;element name="bsp1" type="{http://WSCommonTypes10.CS.ws.alfabank.ru}WSTypeChar5"/>
 *         &lt;element name="bsp2" type="{http://WSCommonTypes10.CS.ws.alfabank.ru}WSTypeChar12"/>
 *         &lt;element name="dokn" type="{http://WSCommonTypes10.CS.ws.alfabank.ru}WSTypeDate"/>
 *         &lt;element name="parr" type="{http://WSCommonTypes10.CS.ws.alfabank.ru}WSTypeChar35"/>
 *         &lt;element name="fio1" type="{http://WSCommonTypes10.CS.ws.alfabank.ru}WSTypeChar35"/>
 *         &lt;element name="dtbl" type="{http://WSCommonTypes10.CS.ws.alfabank.ru}WSTypeDate"/>
 *         &lt;element name="user" type="{http://WSCommonTypes10.CS.ws.alfabank.ru}WSTypeChar4"/>
 *         &lt;element name="cls" type="{http://WSCommonTypes10.CS.ws.alfabank.ru}WSTypeChar3"/>
 *         &lt;element name="nalo" type="{http://WSCommonTypes10.CS.ws.alfabank.ru}WSTypeChar20"/>
 *         &lt;element name="embo" type="{http://WSCommonTypes10.CS.ws.alfabank.ru}WSTypeChar19"/>
 *         &lt;element name="crre" type="{http://WSCommonTypes10.CS.ws.alfabank.ru}WSTypeChar4"/>
 *         &lt;element name="norg" type="{http://WSCommonTypes10.CS.ws.alfabank.ru}WSTypeChar35"/>
 *         &lt;element name="kvdu" type="{http://WSCommonTypes10.CS.ws.alfabank.ru}WSTypeChar3"/>
 *         &lt;element name="snom" type="{http://WSCommonTypes10.CS.ws.alfabank.ru}WSTypeChar35"/>
 *         &lt;element name="orgd" type="{http://WSCommonTypes10.CS.ws.alfabank.ru}WSTypeChar35"/>
 *         &lt;element name="dtvd" type="{http://WSCommonTypes10.CS.ws.alfabank.ru}WSTypeDate"/>
 *         &lt;element name="cln" type="{http://WSCommonTypes10.CS.ws.alfabank.ru}WSTypeChar1"/>
 *         &lt;element name="dlgn" type="{http://WSCommonTypes10.CS.ws.alfabank.ru}WSTypeChar35"/>
 *         &lt;element name="dkln" type="{http://WSCommonTypes10.CS.ws.alfabank.ru}WSTypeDate"/>
 *         &lt;element name="fior" type="{http://WSCommonTypes10.CS.ws.alfabank.ru}WSTypeChar35"/>
 *         &lt;element name="blyn" type="{http://WSCommonTypes10.CS.ws.alfabank.ru}WSTypeChar1"/>
 *         &lt;element name="okvd" type="{http://WSCommonTypes10.CS.ws.alfabank.ru}WSTypeChar8"/>
 *         &lt;element name="eleb" type="{http://WSCommonTypes10.CS.ws.alfabank.ru}WSTypeChar1"/>
 *         &lt;element name="tpcm" type="{http://WSCommonTypes10.CS.ws.alfabank.ru}WSTypeChar1"/>
 *         &lt;element name="spco" type="{http://WSCommonTypes10.CS.ws.alfabank.ru}WSTypeChar1"/>
 *         &lt;element name="dtcl" type="{http://WSCommonTypes10.CS.ws.alfabank.ru}WSTypeDate"/>
 *         &lt;element name="cnat" type="{http://WSCommonTypes10.CS.ws.alfabank.ru}WSTypeChar2"/>
 *         &lt;element name="dtct" type="{http://WSCommonTypes10.CS.ws.alfabank.ru}WSTypeDate"/>
 *         &lt;element name="sale" type="{http://WSCommonTypes10.CS.ws.alfabank.ru}WSTypeChar4"/>
 *         &lt;element name="dtbr" type="{http://WSCommonTypes10.CS.ws.alfabank.ru}WSTypeDate"/>
 *         &lt;element name="mtbr" type="{http://WSCommonTypes10.CS.ws.alfabank.ru}WSTypeChar35"/>
 *         &lt;element name="opss" type="{http://WSCommonTypes10.CS.ws.alfabank.ru}WSTypeChar2"/>
 *         &lt;element name="sogr" type="{http://WSCommonTypes10.CS.ws.alfabank.ru}WSTypeChar2"/>
 *         &lt;element name="nogr" type="{http://WSCommonTypes10.CS.ws.alfabank.ru}WSTypeChar9"/>
 *         &lt;element name="ukl1" type="{http://WSCommonTypes10.CS.ws.alfabank.ru}WSTypeChar35"/>
 *         &lt;element name="ukl2" type="{http://WSCommonTypes10.CS.ws.alfabank.ru}WSTypeChar35"/>
 *         &lt;element name="ukl3" type="{http://WSCommonTypes10.CS.ws.alfabank.ru}WSTypeChar35"/>
 *         &lt;element name="ukl4" type="{http://WSCommonTypes10.CS.ws.alfabank.ru}WSTypeChar35"/>
 *         &lt;element name="ukl5" type="{http://WSCommonTypes10.CS.ws.alfabank.ru}WSTypeChar35"/>
 *         &lt;element name="dptp" type="{http://WSCommonTypes10.CS.ws.alfabank.ru}WSTypeChar1"/>
 *         &lt;element name="dpsn" type="{http://WSCommonTypes10.CS.ws.alfabank.ru}WSTypeChar20"/>
 *         &lt;element name="dpd1" type="{http://WSCommonTypes10.CS.ws.alfabank.ru}WSTypeDate"/>
 *         &lt;element name="dpd2" type="{http://WSCommonTypes10.CS.ws.alfabank.ru}WSTypeDate"/>
 *         &lt;element name="mcsn" type="{http://WSCommonTypes10.CS.ws.alfabank.ru}WSTypeChar13"/>
 *         &lt;element name="mcd1" type="{http://WSCommonTypes10.CS.ws.alfabank.ru}WSTypeDate"/>
 *         &lt;element name="mcd2" type="{http://WSCommonTypes10.CS.ws.alfabank.ru}WSTypeDate"/>
 *         &lt;element name="kpps" type="{http://WSCommonTypes10.CS.ws.alfabank.ru}WSTypeChar9"/>
 *         &lt;element name="kno" type="{http://WSCommonTypes10.CS.ws.alfabank.ru}WSTypeChar4"/>
 *         &lt;element name="migr" type="{http://WSCommonTypes10.CS.ws.alfabank.ru}WSTypeChar1"/>
 *         &lt;element name="vip" type="{http://WSCommonTypes10.CS.ws.alfabank.ru}WSTypeChar1"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "WSCustomerBaseInfoGetOutAdditionalInfoClientT", propOrder = {
    "fnm1",
    "fnm2",
    "fnm3",
    "bikr",
    "bnkn",
    "ca",
    "shr",
    "shv",
    "shb",
    "okhx",
    "okto",
    "okpo",
    "okfs",
    "okpf",
    "okog",
    "dlg1",
    "fam1",
    "nam1",
    "par1",
    "pho1",
    "dlg2",
    "fam2",
    "nam2",
    "par2",
    "pho2",
    "clco",
    "dacc",
    "daco",
    "klba",
    "perp",
    "cred",
    "kpp",
    "gni",
    "ggni",
    "foms",
    "npfn",
    "dmgt",
    "dtre",
    "nreg",
    "tnal",
    "tnap",
    "tnam",
    "cnam",
    "kotn",
    "mail",
    "namr",
    "phor",
    "bsp1",
    "bsp2",
    "dokn",
    "parr",
    "fio1",
    "dtbl",
    "user",
    "cls",
    "nalo",
    "embo",
    "crre",
    "norg",
    "kvdu",
    "snom",
    "orgd",
    "dtvd",
    "cln",
    "dlgn",
    "dkln",
    "fior",
    "blyn",
    "okvd",
    "eleb",
    "tpcm",
    "spco",
    "dtcl",
    "cnat",
    "dtct",
    "sale",
    "dtbr",
    "mtbr",
    "opss",
    "sogr",
    "nogr",
    "ukl1",
    "ukl2",
    "ukl3",
    "ukl4",
    "ukl5",
    "dptp",
    "dpsn",
    "dpd1",
    "dpd2",
    "mcsn",
    "mcd1",
    "mcd2",
    "kpps",
    "kno",
    "migr",
    "vip"
})
public class WSCustomerBaseInfoGetOutAdditionalInfoClientT {

    @XmlElement(required = true)
    protected String fnm1;
    @XmlElement(required = true)
    protected String fnm2;
    @XmlElement(required = true)
    protected String fnm3;
    @XmlElement(required = true)
    protected String bikr;
    @XmlElement(required = true)
    protected String bnkn;
    @XmlElement(required = true)
    protected String ca;
    @XmlElement(required = true)
    protected String shr;
    @XmlElement(required = true)
    protected String shv;
    @XmlElement(required = true)
    protected String shb;
    @XmlElement(required = true)
    protected String okhx;
    @XmlElement(required = true)
    protected String okto;
    @XmlElement(required = true)
    protected String okpo;
    @XmlElement(required = true)
    protected String okfs;
    @XmlElement(required = true)
    protected String okpf;
    @XmlElement(required = true)
    protected String okog;
    @XmlElement(required = true)
    protected String dlg1;
    @XmlElement(required = true)
    protected String fam1;
    @XmlElement(required = true)
    protected String nam1;
    @XmlElement(required = true)
    protected String par1;
    @XmlElement(required = true)
    protected String pho1;
    @XmlElement(required = true)
    protected String dlg2;
    @XmlElement(required = true)
    protected String fam2;
    @XmlElement(required = true)
    protected String nam2;
    @XmlElement(required = true)
    protected String par2;
    @XmlElement(required = true)
    protected String pho2;
    @XmlElement(required = true)
    protected String clco;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dacc;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar daco;
    @XmlElement(required = true)
    protected String klba;
    @XmlElement(required = true)
    protected String perp;
    @XmlElement(required = true)
    protected String cred;
    @XmlElement(required = true)
    protected String kpp;
    @XmlElement(required = true)
    protected String gni;
    @XmlElement(required = true)
    protected String ggni;
    @XmlElement(required = true)
    protected String foms;
    @XmlElement(required = true)
    protected String npfn;
    @XmlElement(required = true)
    protected String dmgt;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dtre;
    @XmlElement(required = true)
    protected String nreg;
    @XmlElement(required = true)
    protected String tnal;
    @XmlElement(required = true)
    protected String tnap;
    @XmlElement(required = true)
    protected String tnam;
    @XmlElement(required = true)
    protected String cnam;
    @XmlElement(required = true)
    protected String kotn;
    @XmlElement(required = true)
    protected String mail;
    @XmlElement(required = true)
    protected String namr;
    @XmlElement(required = true)
    protected String phor;
    @XmlElement(required = true)
    protected String bsp1;
    @XmlElement(required = true)
    protected String bsp2;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dokn;
    @XmlElement(required = true)
    protected String parr;
    @XmlElement(required = true)
    protected String fio1;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dtbl;
    @XmlElement(required = true)
    protected String user;
    @XmlElement(required = true)
    protected String cls;
    @XmlElement(required = true)
    protected String nalo;
    @XmlElement(required = true)
    protected String embo;
    @XmlElement(required = true)
    protected String crre;
    @XmlElement(required = true)
    protected String norg;
    @XmlElement(required = true)
    protected String kvdu;
    @XmlElement(required = true)
    protected String snom;
    @XmlElement(required = true)
    protected String orgd;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dtvd;
    @XmlElement(required = true)
    protected String cln;
    @XmlElement(required = true)
    protected String dlgn;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dkln;
    @XmlElement(required = true)
    protected String fior;
    @XmlElement(required = true)
    protected String blyn;
    @XmlElement(required = true)
    protected String okvd;
    @XmlElement(required = true)
    protected String eleb;
    @XmlElement(required = true)
    protected String tpcm;
    @XmlElement(required = true)
    protected String spco;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dtcl;
    @XmlElement(required = true)
    protected String cnat;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dtct;
    @XmlElement(required = true)
    protected String sale;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dtbr;
    @XmlElement(required = true)
    protected String mtbr;
    @XmlElement(required = true)
    protected String opss;
    @XmlElement(required = true)
    protected String sogr;
    @XmlElement(required = true)
    protected String nogr;
    @XmlElement(required = true)
    protected String ukl1;
    @XmlElement(required = true)
    protected String ukl2;
    @XmlElement(required = true)
    protected String ukl3;
    @XmlElement(required = true)
    protected String ukl4;
    @XmlElement(required = true)
    protected String ukl5;
    @XmlElement(required = true)
    protected String dptp;
    @XmlElement(required = true)
    protected String dpsn;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dpd1;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dpd2;
    @XmlElement(required = true)
    protected String mcsn;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar mcd1;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar mcd2;
    @XmlElement(required = true)
    protected String kpps;
    @XmlElement(required = true)
    protected String kno;
    @XmlElement(required = true)
    protected String migr;
    @XmlElement(required = true)
    protected String vip;

    /**
     * Gets the value of the fnm1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFnm1() {
        return fnm1;
    }

    /**
     * Sets the value of the fnm1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFnm1(String value) {
        this.fnm1 = value;
    }

    /**
     * Gets the value of the fnm2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFnm2() {
        return fnm2;
    }

    /**
     * Sets the value of the fnm2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFnm2(String value) {
        this.fnm2 = value;
    }

    /**
     * Gets the value of the fnm3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFnm3() {
        return fnm3;
    }

    /**
     * Sets the value of the fnm3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFnm3(String value) {
        this.fnm3 = value;
    }

    /**
     * Gets the value of the bikr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBikr() {
        return bikr;
    }

    /**
     * Sets the value of the bikr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBikr(String value) {
        this.bikr = value;
    }

    /**
     * Gets the value of the bnkn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBnkn() {
        return bnkn;
    }

    /**
     * Sets the value of the bnkn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBnkn(String value) {
        this.bnkn = value;
    }

    /**
     * Gets the value of the ca property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCa() {
        return ca;
    }

    /**
     * Sets the value of the ca property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCa(String value) {
        this.ca = value;
    }

    /**
     * Gets the value of the shr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShr() {
        return shr;
    }

    /**
     * Sets the value of the shr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShr(String value) {
        this.shr = value;
    }

    /**
     * Gets the value of the shv property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShv() {
        return shv;
    }

    /**
     * Sets the value of the shv property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShv(String value) {
        this.shv = value;
    }

    /**
     * Gets the value of the shb property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShb() {
        return shb;
    }

    /**
     * Sets the value of the shb property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShb(String value) {
        this.shb = value;
    }

    /**
     * Gets the value of the okhx property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOkhx() {
        return okhx;
    }

    /**
     * Sets the value of the okhx property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOkhx(String value) {
        this.okhx = value;
    }

    /**
     * Gets the value of the okto property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOkto() {
        return okto;
    }

    /**
     * Sets the value of the okto property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOkto(String value) {
        this.okto = value;
    }

    /**
     * Gets the value of the okpo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOkpo() {
        return okpo;
    }

    /**
     * Sets the value of the okpo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOkpo(String value) {
        this.okpo = value;
    }

    /**
     * Gets the value of the okfs property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOkfs() {
        return okfs;
    }

    /**
     * Sets the value of the okfs property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOkfs(String value) {
        this.okfs = value;
    }

    /**
     * Gets the value of the okpf property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOkpf() {
        return okpf;
    }

    /**
     * Sets the value of the okpf property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOkpf(String value) {
        this.okpf = value;
    }

    /**
     * Gets the value of the okog property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOkog() {
        return okog;
    }

    /**
     * Sets the value of the okog property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOkog(String value) {
        this.okog = value;
    }

    /**
     * Gets the value of the dlg1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDlg1() {
        return dlg1;
    }

    /**
     * Sets the value of the dlg1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDlg1(String value) {
        this.dlg1 = value;
    }

    /**
     * Gets the value of the fam1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFam1() {
        return fam1;
    }

    /**
     * Sets the value of the fam1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFam1(String value) {
        this.fam1 = value;
    }

    /**
     * Gets the value of the nam1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNam1() {
        return nam1;
    }

    /**
     * Sets the value of the nam1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNam1(String value) {
        this.nam1 = value;
    }

    /**
     * Gets the value of the par1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPar1() {
        return par1;
    }

    /**
     * Sets the value of the par1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPar1(String value) {
        this.par1 = value;
    }

    /**
     * Gets the value of the pho1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPho1() {
        return pho1;
    }

    /**
     * Sets the value of the pho1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPho1(String value) {
        this.pho1 = value;
    }

    /**
     * Gets the value of the dlg2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDlg2() {
        return dlg2;
    }

    /**
     * Sets the value of the dlg2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDlg2(String value) {
        this.dlg2 = value;
    }

    /**
     * Gets the value of the fam2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFam2() {
        return fam2;
    }

    /**
     * Sets the value of the fam2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFam2(String value) {
        this.fam2 = value;
    }

    /**
     * Gets the value of the nam2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNam2() {
        return nam2;
    }

    /**
     * Sets the value of the nam2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNam2(String value) {
        this.nam2 = value;
    }

    /**
     * Gets the value of the par2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPar2() {
        return par2;
    }

    /**
     * Sets the value of the par2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPar2(String value) {
        this.par2 = value;
    }

    /**
     * Gets the value of the pho2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPho2() {
        return pho2;
    }

    /**
     * Sets the value of the pho2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPho2(String value) {
        this.pho2 = value;
    }

    /**
     * Gets the value of the clco property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClco() {
        return clco;
    }

    /**
     * Sets the value of the clco property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClco(String value) {
        this.clco = value;
    }

    /**
     * Gets the value of the dacc property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDacc() {
        return dacc;
    }

    /**
     * Sets the value of the dacc property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDacc(XMLGregorianCalendar value) {
        this.dacc = value;
    }

    /**
     * Gets the value of the daco property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDaco() {
        return daco;
    }

    /**
     * Sets the value of the daco property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDaco(XMLGregorianCalendar value) {
        this.daco = value;
    }

    /**
     * Gets the value of the klba property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKlba() {
        return klba;
    }

    /**
     * Sets the value of the klba property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKlba(String value) {
        this.klba = value;
    }

    /**
     * Gets the value of the perp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPerp() {
        return perp;
    }

    /**
     * Sets the value of the perp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPerp(String value) {
        this.perp = value;
    }

    /**
     * Gets the value of the cred property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCred() {
        return cred;
    }

    /**
     * Sets the value of the cred property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCred(String value) {
        this.cred = value;
    }

    /**
     * Gets the value of the kpp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKpp() {
        return kpp;
    }

    /**
     * Sets the value of the kpp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKpp(String value) {
        this.kpp = value;
    }

    /**
     * Gets the value of the gni property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGni() {
        return gni;
    }

    /**
     * Sets the value of the gni property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGni(String value) {
        this.gni = value;
    }

    /**
     * Gets the value of the ggni property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGgni() {
        return ggni;
    }

    /**
     * Sets the value of the ggni property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGgni(String value) {
        this.ggni = value;
    }

    /**
     * Gets the value of the foms property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFoms() {
        return foms;
    }

    /**
     * Sets the value of the foms property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFoms(String value) {
        this.foms = value;
    }

    /**
     * Gets the value of the npfn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNpfn() {
        return npfn;
    }

    /**
     * Sets the value of the npfn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNpfn(String value) {
        this.npfn = value;
    }

    /**
     * Gets the value of the dmgt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDmgt() {
        return dmgt;
    }

    /**
     * Sets the value of the dmgt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDmgt(String value) {
        this.dmgt = value;
    }

    /**
     * Gets the value of the dtre property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDtre() {
        return dtre;
    }

    /**
     * Sets the value of the dtre property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDtre(XMLGregorianCalendar value) {
        this.dtre = value;
    }

    /**
     * Gets the value of the nreg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNreg() {
        return nreg;
    }

    /**
     * Sets the value of the nreg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNreg(String value) {
        this.nreg = value;
    }

    /**
     * Gets the value of the tnal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTnal() {
        return tnal;
    }

    /**
     * Sets the value of the tnal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTnal(String value) {
        this.tnal = value;
    }

    /**
     * Gets the value of the tnap property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTnap() {
        return tnap;
    }

    /**
     * Sets the value of the tnap property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTnap(String value) {
        this.tnap = value;
    }

    /**
     * Gets the value of the tnam property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTnam() {
        return tnam;
    }

    /**
     * Sets the value of the tnam property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTnam(String value) {
        this.tnam = value;
    }

    /**
     * Gets the value of the cnam property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCnam() {
        return cnam;
    }

    /**
     * Sets the value of the cnam property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCnam(String value) {
        this.cnam = value;
    }

    /**
     * Gets the value of the kotn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKotn() {
        return kotn;
    }

    /**
     * Sets the value of the kotn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKotn(String value) {
        this.kotn = value;
    }

    /**
     * Gets the value of the mail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMail() {
        return mail;
    }

    /**
     * Sets the value of the mail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMail(String value) {
        this.mail = value;
    }

    /**
     * Gets the value of the namr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNamr() {
        return namr;
    }

    /**
     * Sets the value of the namr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNamr(String value) {
        this.namr = value;
    }

    /**
     * Gets the value of the phor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPhor() {
        return phor;
    }

    /**
     * Sets the value of the phor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPhor(String value) {
        this.phor = value;
    }

    /**
     * Gets the value of the bsp1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBsp1() {
        return bsp1;
    }

    /**
     * Sets the value of the bsp1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBsp1(String value) {
        this.bsp1 = value;
    }

    /**
     * Gets the value of the bsp2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBsp2() {
        return bsp2;
    }

    /**
     * Sets the value of the bsp2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBsp2(String value) {
        this.bsp2 = value;
    }

    /**
     * Gets the value of the dokn property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDokn() {
        return dokn;
    }

    /**
     * Sets the value of the dokn property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDokn(XMLGregorianCalendar value) {
        this.dokn = value;
    }

    /**
     * Gets the value of the parr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParr() {
        return parr;
    }

    /**
     * Sets the value of the parr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParr(String value) {
        this.parr = value;
    }

    /**
     * Gets the value of the fio1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFio1() {
        return fio1;
    }

    /**
     * Sets the value of the fio1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFio1(String value) {
        this.fio1 = value;
    }

    /**
     * Gets the value of the dtbl property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDtbl() {
        return dtbl;
    }

    /**
     * Sets the value of the dtbl property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDtbl(XMLGregorianCalendar value) {
        this.dtbl = value;
    }

    /**
     * Gets the value of the user property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUser() {
        return user;
    }

    /**
     * Sets the value of the user property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUser(String value) {
        this.user = value;
    }

    /**
     * Gets the value of the cls property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCls() {
        return cls;
    }

    /**
     * Sets the value of the cls property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCls(String value) {
        this.cls = value;
    }

    /**
     * Gets the value of the nalo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNalo() {
        return nalo;
    }

    /**
     * Sets the value of the nalo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNalo(String value) {
        this.nalo = value;
    }

    /**
     * Gets the value of the embo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmbo() {
        return embo;
    }

    /**
     * Sets the value of the embo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmbo(String value) {
        this.embo = value;
    }

    /**
     * Gets the value of the crre property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCrre() {
        return crre;
    }

    /**
     * Sets the value of the crre property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCrre(String value) {
        this.crre = value;
    }

    /**
     * Gets the value of the norg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNorg() {
        return norg;
    }

    /**
     * Sets the value of the norg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNorg(String value) {
        this.norg = value;
    }

    /**
     * Gets the value of the kvdu property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKvdu() {
        return kvdu;
    }

    /**
     * Sets the value of the kvdu property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKvdu(String value) {
        this.kvdu = value;
    }

    /**
     * Gets the value of the snom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSnom() {
        return snom;
    }

    /**
     * Sets the value of the snom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSnom(String value) {
        this.snom = value;
    }

    /**
     * Gets the value of the orgd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrgd() {
        return orgd;
    }

    /**
     * Sets the value of the orgd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrgd(String value) {
        this.orgd = value;
    }

    /**
     * Gets the value of the dtvd property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDtvd() {
        return dtvd;
    }

    /**
     * Sets the value of the dtvd property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDtvd(XMLGregorianCalendar value) {
        this.dtvd = value;
    }

    /**
     * Gets the value of the cln property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCln() {
        return cln;
    }

    /**
     * Sets the value of the cln property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCln(String value) {
        this.cln = value;
    }

    /**
     * Gets the value of the dlgn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDlgn() {
        return dlgn;
    }

    /**
     * Sets the value of the dlgn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDlgn(String value) {
        this.dlgn = value;
    }

    /**
     * Gets the value of the dkln property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDkln() {
        return dkln;
    }

    /**
     * Sets the value of the dkln property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDkln(XMLGregorianCalendar value) {
        this.dkln = value;
    }

    /**
     * Gets the value of the fior property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFior() {
        return fior;
    }

    /**
     * Sets the value of the fior property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFior(String value) {
        this.fior = value;
    }

    /**
     * Gets the value of the blyn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBlyn() {
        return blyn;
    }

    /**
     * Sets the value of the blyn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBlyn(String value) {
        this.blyn = value;
    }

    /**
     * Gets the value of the okvd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOkvd() {
        return okvd;
    }

    /**
     * Sets the value of the okvd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOkvd(String value) {
        this.okvd = value;
    }

    /**
     * Gets the value of the eleb property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEleb() {
        return eleb;
    }

    /**
     * Sets the value of the eleb property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEleb(String value) {
        this.eleb = value;
    }

    /**
     * Gets the value of the tpcm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTpcm() {
        return tpcm;
    }

    /**
     * Sets the value of the tpcm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTpcm(String value) {
        this.tpcm = value;
    }

    /**
     * Gets the value of the spco property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpco() {
        return spco;
    }

    /**
     * Sets the value of the spco property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpco(String value) {
        this.spco = value;
    }

    /**
     * Gets the value of the dtcl property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDtcl() {
        return dtcl;
    }

    /**
     * Sets the value of the dtcl property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDtcl(XMLGregorianCalendar value) {
        this.dtcl = value;
    }

    /**
     * Gets the value of the cnat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCnat() {
        return cnat;
    }

    /**
     * Sets the value of the cnat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCnat(String value) {
        this.cnat = value;
    }

    /**
     * Gets the value of the dtct property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDtct() {
        return dtct;
    }

    /**
     * Sets the value of the dtct property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDtct(XMLGregorianCalendar value) {
        this.dtct = value;
    }

    /**
     * Gets the value of the sale property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSale() {
        return sale;
    }

    /**
     * Sets the value of the sale property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSale(String value) {
        this.sale = value;
    }

    /**
     * Gets the value of the dtbr property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDtbr() {
        return dtbr;
    }

    /**
     * Sets the value of the dtbr property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDtbr(XMLGregorianCalendar value) {
        this.dtbr = value;
    }

    /**
     * Gets the value of the mtbr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMtbr() {
        return mtbr;
    }

    /**
     * Sets the value of the mtbr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMtbr(String value) {
        this.mtbr = value;
    }

    /**
     * Gets the value of the opss property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOpss() {
        return opss;
    }

    /**
     * Sets the value of the opss property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOpss(String value) {
        this.opss = value;
    }

    /**
     * Gets the value of the sogr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSogr() {
        return sogr;
    }

    /**
     * Sets the value of the sogr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSogr(String value) {
        this.sogr = value;
    }

    /**
     * Gets the value of the nogr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNogr() {
        return nogr;
    }

    /**
     * Sets the value of the nogr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNogr(String value) {
        this.nogr = value;
    }

    /**
     * Gets the value of the ukl1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUkl1() {
        return ukl1;
    }

    /**
     * Sets the value of the ukl1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUkl1(String value) {
        this.ukl1 = value;
    }

    /**
     * Gets the value of the ukl2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUkl2() {
        return ukl2;
    }

    /**
     * Sets the value of the ukl2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUkl2(String value) {
        this.ukl2 = value;
    }

    /**
     * Gets the value of the ukl3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUkl3() {
        return ukl3;
    }

    /**
     * Sets the value of the ukl3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUkl3(String value) {
        this.ukl3 = value;
    }

    /**
     * Gets the value of the ukl4 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUkl4() {
        return ukl4;
    }

    /**
     * Sets the value of the ukl4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUkl4(String value) {
        this.ukl4 = value;
    }

    /**
     * Gets the value of the ukl5 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUkl5() {
        return ukl5;
    }

    /**
     * Sets the value of the ukl5 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUkl5(String value) {
        this.ukl5 = value;
    }

    /**
     * Gets the value of the dptp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDptp() {
        return dptp;
    }

    /**
     * Sets the value of the dptp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDptp(String value) {
        this.dptp = value;
    }

    /**
     * Gets the value of the dpsn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDpsn() {
        return dpsn;
    }

    /**
     * Sets the value of the dpsn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDpsn(String value) {
        this.dpsn = value;
    }

    /**
     * Gets the value of the dpd1 property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDpd1() {
        return dpd1;
    }

    /**
     * Sets the value of the dpd1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDpd1(XMLGregorianCalendar value) {
        this.dpd1 = value;
    }

    /**
     * Gets the value of the dpd2 property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDpd2() {
        return dpd2;
    }

    /**
     * Sets the value of the dpd2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDpd2(XMLGregorianCalendar value) {
        this.dpd2 = value;
    }

    /**
     * Gets the value of the mcsn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMcsn() {
        return mcsn;
    }

    /**
     * Sets the value of the mcsn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMcsn(String value) {
        this.mcsn = value;
    }

    /**
     * Gets the value of the mcd1 property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getMcd1() {
        return mcd1;
    }

    /**
     * Sets the value of the mcd1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setMcd1(XMLGregorianCalendar value) {
        this.mcd1 = value;
    }

    /**
     * Gets the value of the mcd2 property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getMcd2() {
        return mcd2;
    }

    /**
     * Sets the value of the mcd2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setMcd2(XMLGregorianCalendar value) {
        this.mcd2 = value;
    }

    /**
     * Gets the value of the kpps property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKpps() {
        return kpps;
    }

    /**
     * Sets the value of the kpps property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKpps(String value) {
        this.kpps = value;
    }

    /**
     * Gets the value of the kno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKno() {
        return kno;
    }

    /**
     * Sets the value of the kno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKno(String value) {
        this.kno = value;
    }

    /**
     * Gets the value of the migr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMigr() {
        return migr;
    }

    /**
     * Sets the value of the migr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMigr(String value) {
        this.migr = value;
    }

    /**
     * Gets the value of the vip property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVip() {
        return vip;
    }

    /**
     * Sets the value of the vip property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVip(String value) {
        this.vip = value;
    }

}
