//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.12.05 at 06:06:17 PM MSK 
//


package com.example.alpha.mock.model.ru.alfabank.ws.cs.wscommontypes10;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ru.alfabank.ws.cs.wscommontypes10 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ru.alfabank.ws.cs.wscommontypes10
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link WSTechnicalException }
     * 
     */
    public WSTechnicalException createWSTechnicalException() {
        return new WSTechnicalException();
    }

    /**
     * Create an instance of {@link WSExtention }
     * 
     */
    public WSExtention createWSExtention() {
        return new WSExtention();
    }

    /**
     * Create an instance of {@link WSAccessException }
     * 
     */
    public WSAccessException createWSAccessException() {
        return new WSAccessException();
    }

    /**
     * Create an instance of {@link WSAppTechnicalException }
     * 
     */
    public WSAppTechnicalException createWSAppTechnicalException() {
        return new WSAppTechnicalException();
    }

    /**
     * Create an instance of {@link WSVerificationException }
     * 
     */
    public WSVerificationException createWSVerificationException() {
        return new WSVerificationException();
    }

    /**
     * Create an instance of {@link WSAppException }
     * 
     */
    public WSAppException createWSAppException() {
        return new WSAppException();
    }

    /**
     * Create an instance of {@link WSCommonParms }
     * 
     */
    public WSCommonParms createWSCommonParms() {
        return new WSCommonParms();
    }

    /**
     * Create an instance of {@link WSCommonOutParms }
     * 
     */
    public WSCommonOutParms createWSCommonOutParms() {
        return new WSCommonOutParms();
    }

}
